name: posku
description: New ForcaPoS

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  flutter_linkify: ^3.1.0
  flutter_money_formatter: ^0.8.3
  get: ^1.11.6
#  http: ^0.12.0+4
#  intl: ^0.16.1
  intl: ^0.15.8
  json_annotation: ^3.0.1
#  modal_bottom_sheet: ^0.1.5
  package_info: ^0.4.0+16
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  timeago: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.3.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path_android: "assets/launcher/ic_launcher.png"
  image_path_ios: "assets/launcher/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
